# セキュリティ対策のためのワークフローのひとつ
# 「機密情報（シークレット）」がハードコーディングされている箇所を検出し、ローテーションを促す
# 例として、以下のような「機密情報（シークレット）」を検出する
# - APIキー
# - パスワード
# - 認証トークン
# - その他、シークレットなどの機密情報
# リンターとして『Secretlint』を使用する
# REPO: https://github.com/secretlint/secretlint

name: Scan Secrets

# このワークフローをトリガーするイベント
on:
  # リポジトリに加わるすべての変更およびコードをスキャンする
  pull_request

permissions: {}

defaults:
  run:
    shell: bash

# とあるPRの中で同じワークフローが複数起動したら、古い方を自動でキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 「機密情報（シークレット）」のハードコーディングを検出するジョブ
  scan:
    runs-on: ubuntu-latest
    # タイムアウトの時間がデフォルトで6時間になっているため、これをより短いほどほどの時間に変更（一旦 `5分` で設定）
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run secretlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          secretlint/secretlint:v11.4.1@sha256:078172d098b6231581bafd0f5b66b12b33f86dc4f8119bda12a422639f8e0b71 secretlint --maskSecrets '**/*'
